CREATE DATABASE BITTY ;
USE BITTY ;
CREATE TABLE BITTY(
id INT PRIMARY KEY 
);
INSERT INTO BITTY (id) VALUES(900);
INSERT INTO BITTY (id) VALUES(901);
INSERT INTO BITTY (id) VALUES(902);
INSERT INTO BITTY (id) VALUES(903);
INSERT INTO BITTY (id) VALUES(904);
SELECT * FROM BITTY ;
SELECT * FROM BITTY LIMIT 2;
